
### GET BY ID
GET http://localhost:3000/product/rolamento 9p


### GET ALL PRODUCTS
GET http://localhost:3000/product


####POST PRODUCT
POST http://localhost:3000/product
Content-Type: application/json

{
    "name": "rolamento ppppp",
    "quantity": 5,
    "price": 30.30,
    "application": "123123",
    "balance": "30",
    "dateOfPurchase": "2024-08-21T00:00:00.000Z",
    "purshaseRequest": 30,
    "whintorCode": 30,
    "details": "rolamento 3",
    "archive_link": "ZXhhbXBsZV9zdHJpbmdfdG9fY29udmVydA=="
}

### PUT PRODUCT
PATCH http://localhost:3000/product/4
Content-Type: application/json


{
  "name": "rolamento 442",
  "quantity": 2,
  "price": 30.40,
  "details": "rolamento 6666"
}

### PATCH PRODUCT
PATCH http://localhost:3000/product/remove/4
Content-Type: application/json


{
  "quantity": 2
}


### DELETE PRODUCT
DELETE http://localhost:3000/product/3